project_id = "wrwuoyevrviukcbdmubg"

[functions.analyze-clip]
verify_jwt = true

[functions.analyze-video-gpt4o]
verify_jwt = true

[functions.generate-feedback]
verify_jwt = true

[functions.analyze-batch]
verify_jwt = true

[functions.aggregate-intangibles]
verify_jwt = false
